## me fail english? that's unpossible.

name: Docker Image CI

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:

  build-xenial:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 16
      run: docker build . -f ./scripts/docker/astrobee_xenial.Dockerfile -t astrobee/astrobee:latest-xenial

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee_xenial.Dockerfile -t test

  build-bionic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 18
      run: docker build . -f ./scripts/docker/astrobee_bionic.Dockerfile -t astrobee/astrobee:latest-bionic

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee_bionic.Dockerfile -t test

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 20
      run: docker build . -f ./scripts/docker/astrobee_focal.Dockerfile -t astrobee/astrobee:latest-focal

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee_focal.Dockerfile -t test
